repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff  # linter
        args: [ --fix, --config=pyproject.toml, --select=I]
      - id: ruff-format  # formatter
        args: [--config=pyproject.toml ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
    - id: mypy
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args: [--drop-empty-cells, '--extra-keys=metadata.kernelspec metadata.version']