"""Class definition of a Drive optimizable model."""

from abc import abstractmethod

import jax.numpy as jnp
from jax import vmap

from paraqeet.optimizable import Optimizable
from paraqeet.quantity import Array, Quantity
from paraqeet.signal.generator import Generator


# TODO: Is Drive a Differentiable object? If so, it should inherit from Differentiable at least
# for the purpose of clarity and consistency. Would it make sense to add a default
# implementation of the abstract Differentiable method get_value_and_gradient?
# If not, we should rename the methods to e.g. get_hamiltonian_gradient to avoid confusion.
class Drive(Optimizable):
    """Represents a time-dependent drive on a subsystem.

    This can for example be a microwave or flux drive.

    """

    def get_value(self, annihilation_operator: Array, times: Array) -> Array:
        """Return the matrix representation of the drive.

        The dimension is given by the Hamiltonian to which this drive is
        attached. The default implementation calls getMatrixOneTime for each
        time step. Subclasses can override this function for a more efficient
        implementation.

        Parameters
        ----------
        annihilation_operator : Array
            Operator of the subsystem to which this drive is attached
        times: Array
            Vector of time samples.

        Returns
        -------
        Array
            Matrix of shape [t, n, n]  with 't' as time and 'n' as the Hilbert
            space dimension.

        """
        # vmap iterates over the times array and returns float. Not caught by mypy.
        return vmap(self.get_value_at_timestep, in_axes=(None, 0))(annihilation_operator, times)  # type: ignore

    @abstractmethod
    def get_value_at_timestep(self, annihilation_operator: Array, t: float) -> Array:
        """Return the matrix representation of the drive.

        The dimension is given by the Hamiltonian to which this drive is
        attached.

        Parameters
        ----------
        annihilation_operator
            Operator of the subsystem to which this drive is attached.
        t: float
            One time point.

        Returns
        -------
        Array
            Matrix of shape [n, n]  with `n` as the Hilbert space dimension.

        """
        pass

    def get_gradient(self, annihilation_operator: Array, times: Array) -> Array:
        """Return the gradient of the system.

        Returns the gradient of the matrix representation of the Hamiltonian
        with respect to each parameter as a list.

        Parameters
        ----------
        annihilation_operator : Array
            Operator of the subsystem to which this drive is attached.
        times: Array
            Vector of time samples.

        Returns
        -------
        Array
            Array of shape [t, p, n, n] with 't' as time, 'p' as number of
            parameters and 'n' as the Hilbert space dimension.


        """
        # Ignoring mypy here as vmap makes the array to float
        return vmap(self.get_gradient_at_timestep, in_axes=(None, 0))(annihilation_operator, times)  #  type: ignore

    @abstractmethod
    def get_gradient_at_timestep(self, annihilation_operator: Array, timestep: float) -> Array:
        """Get the one-time gradient of the system.

        Returns the gradient of the matrix representation of the
        Hamiltonian with respect to each parameter as a list.

        Parameters
        ----------
        annihilation_operator : Array
            Operator of the subsystem to which this drive is attached.
        timestep: float
            One time step.

        Returns
        -------
        Array
            Array of shape [p, n, n] with 'p' as the number
            of parameters and 'n' as the  Hilbert space dimension.

        """
        pass

    @staticmethod
    def _repeat(mat: Array, num: int) -> Array:
        """Repeats the matrix mat for each timestep in the times array.

        Returns an array with shape [t, n, m] where 't' is the
        number of time steps and 'mat' is an 'n' times 'm' matrix.

        Parameters
        ----------
        mat: Array
            Input matrix for repetition.
        num : int
            Number of times of repetition.

        Returns
        -------
        Array
            Repeated matrix for further computation.

        """
        return mat.reshape((1,) + mat.shape).repeat(num, axis=0)


class DriveOperator(Drive):
    r"""Create a generator drive model.

    Transversal (a^\\dagger + a or \\sigma_x type) or longitudinal (a^\\dagger a or \\sigma_z type) drive with a
    time-dependent scalar coefficient that is generated by a Generator object.

    Parameters
    ----------
    generator : Generator
        Signal generator stack.
    is_longitudinal : bool
        Generator is longitudinal or transversal depending on this boolean.

    """

    _generator: Generator
    _is_longitudinal: bool

    def __init__(self, generator: Generator, is_longitudinal: bool):
        self._generator = generator
        self._is_longitudinal = is_longitudinal

    @property
    def generator(self) -> Generator:
        """Get the signal generator from the system.

        Returns
        -------
        paraqeet.signal.generator.Generator
            Returns the signal generator object from the system.

        """
        return self._generator

    def get_parameters(self) -> list[Quantity]:
        """Get a list of parameters of the system.

        Returns
        -------
        list[Quantity]
            List of optimizable parameters of the system.

        """
        return self._generator.get_parameters()

    def _compute_matrix(self, a: Array) -> Array:
        """Return the operator for the longitudinal or transverse drive.

        Parameters
        ----------
        a: Array
            Operator for computation.

        Returns
        -------
        Array
            Returns the operator for the longitudinal or transverse drive.

        """
        return (jnp.conjugate(a.T) @ a) if self._is_longitudinal else (jnp.conjugate(a.T) + a)

    def get_value_at_timestep(self, a: Array, t: float) -> Array:
        """Get the one-time matrix of the system.

        Fetches the coefficient from the drive and transforms it
        into the correct shape for the Hamiltonian.

        Parameters
        ----------
        a: Array
            Operator for longitudinal or transverse drive.
        t: Array
            One-dimensional vector of timestamps.

        Returns
        -------
        Array
            Returns the shape-shifted coefficient from the drive.

        """
        # TODO: generator.get_value expects an array, even for one time point.
        # Is the naming of the method correct then?
        signal = self._generator.get_value(t)
        matrix = self._compute_matrix(a)
        return signal * matrix

    def get_gradient_at_timestep(self, a: Array, timestep: float) -> Array:
        """Get the one-time gradient of the system.

        Fetches the gradient from the drive and transforms it into the
        correct shape for the Hamiltonian.

        Parameters
        ----------
        a: Array
            Operator for longitudinal or transverse drive.
        timestep: Array
            One-dimensional vector of timestamps.

        Returns
        -------
        Array
            Returns the shape-shifted gradient from the drive.

        """
        signal_grad = self._generator.get_gradient_at_timestep(timestep).reshape((-1, 1, 1))
        matrix = Drive._repeat(self._compute_matrix(a), signal_grad.shape[0])
        return signal_grad * matrix
