from cthree.quantity import Quantity
from cthree.signal.envelopes import Envelope
from cthree.signal.generator import Generator


import jax.numpy as jnp
import numpy as np
from jax import Array, jit, vmap
from jax.scipy.special import erf


from functools import partial


class PWCGenerator(Generator):
    """Convert a complex envelope to PWC pulse.

    This sets the pulse parameters to the `tlist` points.
    The gradient of the pulse wrt the PWC bins is 1 at that time point and zero
    everywhere else.

    This Generator doesn't add the LO signal to the envelope pulse.
    Driving with a PWC pulse (without the LO) should be done in the rotating
    frame of drive.

    __envs: list[Waveform]
        List of Envelopes
    __tlist: np.ndarray
        Time grid discritization points

    Parameters
    ----------
    envelopes : List[cthree.signal.Waveform]
        List of input devices.

    """

    __envs: list[Envelope]
    __tlist: np.ndarray
    __inphase: Quantity
    __quadrature: Quantity
    _optimisable_parameters: list[Quantity] = []
    __multiply_flat_top: bool = False

    def __init__(
        self,
        envelopes: list[Envelope] | None,
        tlist: np.ndarray,
    ):
        self.__envs = envelopes or []
        self.__tlist = tlist

        # Choose the center point as time grid
        dt = tlist[1] - tlist[0]
        self.__tlist = tlist[:-1] + dt / 2

        self.__set_inphase_and_quadrature()
        self.__t_final = self.__tlist[-1]


    def __compute_envelope(self, t):
        t_final = self.__t_final
        ramp_time = t_final / 25
        rampUp = 1 + erf((t - 2 * t_final / 20) / ramp_time)
        rampDown = 1 + erf((-t + 18 * t_final / 20) / ramp_time)
        return rampUp * rampDown / 4


    @property
    def tlist(self) -> np.ndarray:
        """Get time grid discritization for generating PWC pulse.

        Returns
        -------
        np.ndarray
            Array of time points at which envelope is discritized.
        """
        return self.__tlist

    @tlist.setter
    def tlist(self, tlist: np.ndarray) -> None:
        """Set time grid discritization for generating PWC pulse.

        Parameters
        ----------
        tlist : np.ndarray
            Array of time points at which envelope is discritized.
        """
        self.__tlist = tlist
        self.__set_inphase_and_quadrature()
    
    @property
    def multiply_flat_top(self) -> bool:
        """Flag to multiply the pulse with a FlatTop.

        This can be used to make the start and end values zeros and force the
        PWC pulse to change smoothly.

        Returns
        -------
        multiply_flat_top : bool
            Flag value for multiply_flat_top.
        """
        return self.__multiply_flat_top

    @multiply_flat_top.setter
    def multiply_flat_top(self, multiply_flat_top: bool) -> None:
        """Set flag to multiply the pulse with a FlatTop.

        This can be used to make the start and end values zeros and force the
        PWC pulse to change smoothly.

        Parameters
        ----------
        multiply_flat_top : bool
            Flag value for multiply_flat_top.
        """
        self.__multiply_flat_top = multiply_flat_top
        self.__set_inphase_and_quadrature()

    def __set_inphase_and_quadrature(self) -> None:
        """Generate Inphase and Quadrature Quantities using tlist."""
        env = jnp.zeros_like(self.__tlist)
        for dev in self.__envs:
            env += dev.compute_output(self.__tlist)

        max_abs = jnp.max(jnp.abs(env))

        self.__inphase = Quantity(
            jnp.real(env),
            min_value=-2 * max_abs,
            max_value=2 * max_abs,
            unit="Hz",
            name="Inphase",
        )
        self.__quadrature = Quantity(
            jnp.imag(env),
            min_value=-2 * max_abs,
            max_value=2 * max_abs,
            unit="Hz",
            name="Quadrature",
        )

    def get_parameters(self) -> list[Quantity]:
        """Return a list of parameters.

        Return the inphase and quadrature as parameters.

        Returns
        -------
        List[Quantity]
            All Parameters describing the signal.
        """
        return [self.__inphase, self.__quadrature]

    def set_optimisable_parameters(self, params: list[Quantity]) -> None:
        """Set specified parameters to be optimised.

        Optimisable paramters can be inphase and quadrature.

        Parameters
        ----------
        params : list[Quantity]
        """
        super().set_optimisable_parameters(params)

    @partial(jit, static_argnums=(0,))
    def __pwc_signal(
        self,
        inphase: np.ndarray,
        quadrature: np.ndarray,
        tlist: np.ndarray,
        t: float,
    ) -> Array:
        """Generate a signal for a single time point 't'.

        The PWC signal is generated by finiding the closest time point
        and returning the correspoinding amplitude value.

        Parameters
        ----------
        inphase: np.ndarray
            1-D vector of step values of real part of the PWC signal.
        quadrature: np.ndarray
            1-D vector of step values of complex part of the PWC signal.
        tlist: np.ndarray
            Time bins of the PWC pulse.
        t : float
            One time point.

        Returns
        -------
        jax.Array
            Returns the PWC signal value at t.

        """
        index = jnp.argmin(jnp.abs(tlist - t))
        return inphase[index] + 1j * quadrature[index]

    def generate_signal(self, t: np.ndarray) -> Array:
        """Generate the PWC signal for time(s) 't'.

        Parameters
        ----------
        t : numpy.ndarray
            One-dimensional vector of timestamps.

        Returns
        -------
        jax.Array
            Returns the signal vector.

        """
        tlist = self.__tlist
        t = jnp.array(t, ndmin=1)
        inphase = self.__inphase.get_value()
        quadrature = self.__quadrature.get_value()
        if self.__multiply_flat_top:
            env = self.__compute_envelope(tlist)
            inphase *= env
            quadrature *= env
        shape = jnp.squeeze(
            vmap(self.__pwc_signal, in_axes=(None, None, None, 0))(
                inphase, quadrature, tlist, t
            )
        )
        return shape

    def generate_signal_gradient(self, t: np.ndarray) -> Array:
        """Return signal gradient wrt inphase and quadrature.

        This returns a list of ones as the gradient of the envelope wrt a step
        is 1 for that time bin and 0 everywhere else.

        Parameters
        ----------
        t : np.ndarray
            Array of time steps.

        Returns
        -------
        Array
            PWC signal gradients.
        """
        t = jnp.array(t, ndmin=1)

        grads = []
        tlist = self.__tlist

        if self.__multiply_flat_top:
            smoothing = self.__compute_envelope(tlist)
            index = jnp.argmin(jnp.abs(tlist - t))
            env = smoothing[index]
        else:
            env = jnp.ones_like(t)

        if self._is_optimised(self.__inphase):
            grads.append(env)
        if self._is_optimised(self.__quadrature):
            grads.append(1j * env)

        if len(grads) > 0:
            grads_stack = jnp.stack(grads)
        else:
            grads_stack = jnp.empty((t.shape[0], 0))
        return grads_stack
    
    def generate_signal_gradient_one_time(self, t: float) -> Array:
        """Return signal gradient wrt inphase and quadrature.

        This returns a list of ones as the gradient of the envelope wrt a step
        is 1 for that time bin and 0 everywhere else.

        Parameters
        ----------
        t : float
            One time step.

        Returns
        -------
        Array
            PWC signal gradients.
        """
        grads = []
        tlist = self.__tlist

        if self.__multiply_flat_top:
            smoothing = self.__compute_envelope(tlist)
            index = jnp.argmin(jnp.abs(tlist - t))
            env = smoothing[index]
        else:
            env = 1

        if self._is_optimised(self.__inphase):
            grads.append(env)
        if self._is_optimised(self.__quadrature):
            grads.append(1j * env)

        return jnp.stack(grads, axis=0) if len(grads) > 0 else jnp.empty((0,))
