from cthree.Quantity import Quantity
from cthree.signal.Generator import Generator
from cthree.signal.Waveform import Waveform


import jax.numpy as jnp
import numpy as np
from jax import Array, jit, vmap


from functools import partial


class PWCGenerator(Generator):
    """Convert a complex envelope to PWC pulse.

    This sets the pulse parameters to the `tlist` points.
    The gradient of the pulse wrt the PWC bins is 1 at that time point and zero
    everywhere else.

    This Generator doesn't add the LO signal to the envelope pulse.
    Driving with a PWC pulse (without the LO) should be done in the rotating
    frame of drive.

    __envs: list[Waveform]
        List of Envelopes
    __tlist: np.ndarray
        Time grid discritization points

    Parameters
    ----------
    envelopes : List[cthree.signal.Waveform]
        List of input devices.

    """

    __envs: list[Waveform]
    __tlist: np.ndarray
    __inphase: Quantity
    __quadrature: Quantity
    _optimisableParameters: list[Quantity] = []

    def __init__(
        self,
        envelopes: list[Waveform] | None,
        tlist: np.ndarray,
    ):
        self.__envs = envelopes or []
        self.__tlist = tlist
        self.__setInphaseAndQuadrature()

    @property
    def tlist(self) -> np.ndarray:
        """Get time grid discritization for generating PWC pulse.

        Returns
        -------
        np.ndarray
            Array of time points at which envelope is discritized.
        """
        return self.__tlist

    @tlist.setter
    def tlist(self, tlist: np.ndarray) -> None:
        """Set time grid discritization for generating PWC pulse.

        Parameters
        ----------
        tlist : np.ndarray
            Array of time points at which envelope is discritized.
        """
        self.__tlist = tlist
        self.__setInphaseAndQuadrature()

    def __setInphaseAndQuadrature(self) -> None:
        """Generate Inphase and Quadrature Quantities using tlist."""
        env = jnp.zeros_like(self.__tlist)
        for dev in self.__envs:
            env += dev.computeOutput(self.__tlist)

        max_abs = jnp.max(jnp.abs(env))

        self.__inphase = Quantity(
            jnp.real(env),
            min_value=-2 * max_abs,
            max_value=2 * max_abs,
            unit="Hz",
            name="Inphase",
        )
        self.__quadrature = Quantity(
            jnp.imag(env),
            min_value=-2 * max_abs,
            max_value=2 * max_abs,
            unit="Hz",
            name="Quadrature",
        )

    def getParameters(self) -> list[Quantity]:
        """Return a list of parameters.

        Return the inphase and quadrature as parameters.

        Returns
        -------
        List[Quantity]
            All Parameters describing the signal.
        """
        return [self.__inphase, self.__quadrature]

    def setOptimisableParameters(self, params: list[Quantity]) -> None:
        """Set specified parameters to be optimised.

        Optimisable paramters can be inphase and quadrature.

        Parameters
        ----------
        params : list[Quantity]
        """
        super().setOptimisableParameters(params)

    @partial(jit, static_argnums=(0,))
    def __PWCSignal(
        self,
        inphase: np.ndarray,
        quadrature: np.ndarray,
        tlist: np.ndarray,
        t: float,
    ) -> Array:
        """Generate a signal for a single time point 't'.

        The PWC signal is generated by finiding the closest time point
        and returning the correspoinding amplitude value.

        Parameters
        ----------
        inphase: np.ndarray
            1-D vector of step values of real part of the PWC signal.
        quadrature: np.ndarray
            1-D vector of step values of complex part of the PWC signal.
        tlist: np.ndarray
            Time bins of the PWC pulse.
        t : float
            One time point.

        Returns
        -------
        jax.Array
            Returns the PWC signal value at t.

        """
        index = jnp.argmin(jnp.abs(tlist - t))
        return inphase[index] + 1j * quadrature[index]

    def generateSignal(self, t: np.ndarray) -> Array:
        """Generate the PWC signal for time(s) 't'.

        Parameters
        ----------
        t : numpy.ndarray
            One-dimensional vector of timestamps.

        Returns
        -------
        jax.Array
            Returns the signal vector.

        """
        t = jnp.array(t, ndmin=1)
        inphase = self.__inphase.getValue()
        quadrature = self.__quadrature.getValue()
        tlist = self.__tlist
        return jnp.squeeze(vmap(self.__PWCSignal, in_axes=(None, None, None, 0))(inphase, quadrature, tlist, t))

    def generateSignalGradient(self, t: np.ndarray) -> Array:
        """Return signal gradient wrt inphase and quadrature.

        This returns a list of ones as the gradient of the envelope wrt a step
        is 1 for that time bin and 0 everywhere else.

        Parameters
        ----------
        t : np.ndarray
            Array of time steps.

        Returns
        -------
        Array
            PWC signal gradients.
        """
        t = jnp.array(t, ndmin=1)

        grads = []

        inphase_scale = self.__inphase.getScale()
        quadrature_scale = self.__quadrature.getScale()

        if self._isOptimised(self.__inphase):
            grads.append(jnp.ones_like(t) * inphase_scale)
        if self._isOptimised(self.__quadrature):
            grads.append(jnp.ones_like(t) * quadrature_scale)

        return jnp.stack(grads, axis=1) if len(grads) > 0 else jnp.empty((t.shape[0], 0))

    def generateSignalGradientOneTime(self, t: float) -> Array:
        """Return signal gradient wrt inphase and quadrature.

        This returns a list of ones as the gradient of the envelope wrt a step
        is 1 for that time bin and 0 everywhere else.

        Parameters
        ----------
        t : float
            One time step.

        Returns
        -------
        Array
            PWC signal gradients.
        """
        grads = []

        inphase_scale = self.__inphase.getScale()
        quadrature_scale = self.__quadrature.getScale()

        if self._isOptimised(self.__inphase):
            grads.append(inphase_scale)
        if self._isOptimised(self.__quadrature):
            grads.append(quadrature_scale)

        return jnp.stack(grads, axis=0) if len(grads) > 0 else jnp.empty((0,))
